language: c
sudo: false

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - $HOME/.ambiata/mafia/bin
    - $HOME/build/ambiata/icicle/.cabal-sandbox

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.3
      - cabal-install-1.22
      - alex-3.1.4
      - happy-1.19.5

before_install:
  - unset CC
  - export PATH=/opt/ghc/7.8.3/bin:/opt/cabal/1.22/bin:$PATH

install:
  # Fetch the latest package list from hackage
  - travis_retry cabal update

  # Install the Cabal library which matches what cabal-install was built against
  - export CABAL_VERSION=$(cabal --version | sed -n '/using version /s/^[^0-9]*\([0-9\.]*\).*$/\1/p')
  - cabal install Cabal-$CABAL_VERSION

  # Check the versions of everything installed
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - ghc-pkg list

  # If we need to build mafia, make it a separate step
  - ./mafia || $(exit 0)

  # Re-initialise the sandbox, as the travis cache cannot be made to
  # cache the `cabal.sandbox.config` file
  - cabal sandbox init

  # Install dependencies and build the project
  - ./mafia build

script:
  # Run all the tests
  - ./mafia testci
