[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20181122052716-977567b/master-haskell-20181122052716-977567b"
  version = 1
  sha1 = "b5434adb04dd0f7dee53b030f3c4cf1fed941c66"

[global]
  CACHE = "true"
  CABAL_VERSION = "1.24.0.2"
  ICICLE_CC_OPTIONS = "-Wall -Werror"

[build.dist-7-10]
  GHC_VERSION="7.10.2"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "icicle"

[build.dist-8-0]
  GHC_VERSION = "8.0.2"

[build.branches-7-10]
  TEST = "false"
  GHC_VERSION = "7.10.2"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "icicle"

[build.branches-7-10-runtime]
  TEST_SUITE = "runtime"
  GHC_VERSION = "7.10.2"

[build.branches-7-10-sundry]
  TEST_SUITE = "sundry"
  GHC_VERSION = "7.10.2"

[build.branches-8-0]
  TEST = "false"
  GHC_VERSION = "8.0.2"

[build.branches-8-0-runtime]
  TEST_SUITE = "runtime"
  GHC_VERSION = "8.0.2"

[build.branches-8-0-sundry]
  TEST_SUITE = "sundry"
  GHC_VERSION = "8.0.2"
